---
- name: Create loopback payload from template
  hosts: 172.16.100.147
  connection: local

  tasks:
    - name: Create template
      with_items: "{{local_loopback}}"
      template: src="files/ietf_interfaces.j2" dest="./output.json"